spring.application.name=ecommerce tech java

# Configuração de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_tech_java_db
spring.datasource.username=postgres
spring.datasource.password=nathan123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true